[WIP] change board representation
marmelab/quoridor-java pull request #2
Opened 2019-06-20 14:08 UTC by mchaffotte

- adding a fence, remove an edge in the model
- add a form in each border of each square to add a fence

2019-06-21 07:08 UTC, fzaninotto commented
Can you please add a screenshot?

2019-06-21 07:15 UTC, mchaffotte commented
I change it internally, I use right now a graph from a java library.
I will add a screenshot of the feature when the front will be (almost) done

2019-06-21 08:34 UTC, mchaffotte commented
@fzaninotto this is the preview of adding fences

2019-06-24 08:09 UTC, floo51 requested changes

2019-06-24 08:09 UTC, floo51 commented on src/main/java/com/marmelab/quoridor/web/AddFence.java
> +    private final List<Fence> addHorizontalFences;
This is named as a method but it isn't.

2019-06-24 08:09 UTC, floo51 commented on src/main/java/com/marmelab/quoridor/web/AddFence.java
> +    public AddFence(int boardSize, List<Fence> horizontalFences, List<Fence> verticalFences) {
This method contains too much logic at once. You maybe could put into named methods whatever it does inside the for loops

2019-06-24 08:09 UTC, floo51 commented on src/main/java/com/marmelab/quoridor/web/BoardView.java
> +        AddFence addFence = new AddFence(game.getBoard().getBoardSize(), horizontalFences, verticalFences);
This is named as a method and isn't.

2019-06-24 08:09 UTC, floo51 commented on src/test/java/com/marmelab/quoridor/web/QuoridorEndpointTest.java
> +                .contains(" <div class=\"pawn\"\n" +
Testing the html result probably isn't the best choice. This gonna break every time you touch templates. You better just test what it says it tests : the presence of the pawn.

2019-06-24 12:30 UTC, floo51 requested changes

2019-06-24 12:30 UTC, floo51 commented on src/test/java/com/marmelab/quoridor/model/BoardTest.java
> +    @DisplayName("It should not be possible to add an vertical fence before a vertical fence")
s/an/a/

2019-06-24 12:47 UTC, floo51 approved these changes

2019-06-24 12:47 UTC, merged